version: '3.8'
services:
  react-app:
    image: react-app
    stdin_open: true
    ports:
      - '3000:3000'
    networks:
      - mern-app
    volumes:
      - ./client/:/usr/src/app
      - /usr/src/app/node_modules
  api-server:
    image: api-server
    env_file: ./server/.env
    ports:
      - '5000:5000'
    networks:
      - mern-app
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
networks:
  mern-app:
    driver: bridge
