export const USER_ATTENDANCE_DETAILS_REQUEST =
  'USER_ATTENDANCE_DETAILS_REQUEST';
export const USER_ATTENDANCE_DETAILS_SUCCESS =
  'USER_ATTENDANCE_DETAILS_SUCCESS';
export const USER_ATTENDANCE_DETAILS_FAIL = 'USER_ATTENDANCE_DETAILS_FAIL';

export const USER_ATTENDANCE_MARK_REQUEST = 'USER_ATTENDANCE_MARK_REQUEST';
export const USER_ATTENDANCE_MARK_SUCCESS = 'USER_ATTENDANCE_MARK_SUCCESS';
export const USER_ATTENDANCE_MARK_FAIL = 'USER_ATTENDANCE_MARK_FAIL';
