export const DEPARTMENT_DETAILS_REQUEST = 'DEPARTMENT_DETAILS_REQUEST';
export const DEPARTMENT_DETAILS_SUCCESS = 'DEPARTMENT_DETAILS_SUCCESS';
export const DEPARTMENT_DETAILS_FAIL = 'DEPARTMENT_DETAILS_FAIL';
