export const DEPARTMENT_DETAILS_REQUEST = 'DEPARTMENT_DETAILS_REQUEST';
export const DEPARTMENT_DETAILS_SUCCESS = 'DEPARTMENT_DETAILS_SUCCESS';
export const DEPARTMENT_DETAILS_FAIL = 'DEPARTMENT_DETAILS_FAIL';

export const DEPARTMENT_EMPLOYEE_LIST_REQUEST =
  'DEPARTMENT_EMPLOYEE_LIST_REQUEST';
export const DEPARTMENT_EMPLOYEE_LIST_SUCCESS =
  'DEPARTMENT_EMPLOYEE_LIST_SUCCESS';
export const DEPARTMENT_EMPLOYEE_LIST_FAIL = 'DEPARTMENT_EMPLOYEE_LIST_FAIL';
