export const USER_LEAVE_DETAILS_REQUEST = 'USER_LEAVE_DETAILS_REQUEST';
export const USER_LEAVE_DETAILS_SUCCESS = 'USER_LEAVE_DETAILS_SUCCESS';
export const USER_LEAVE_DETAILS_FAIL = 'USER_LEAVE_DETAILS_FAIL';

export const ADMIN_LEAVE_DETAILS_REQUEST = 'ADMIN_LEAVE_DETAILS_REQUEST';
export const ADMIN_LEAVE_DETAILS_SUCCESS = 'ADMIN_LEAVE_DETAILS_SUCCESS';
export const ADMIN_LEAVE_DETAILS_FAIL = 'ADMIN_LEAVE_DETAILS_FAIL';

export const CREATE_LEAVE_REQUEST = 'CREATE_LEAVE_REQUEST';
export const CREATE_LEAVE_SUCCESS = 'CREATE_LEAVE_SUCCESS';
export const CREATE_LEAVE_FAIL = 'CREATE_LEAVE_FAIL';

export const GET_ALL_LEAVE_REQUEST = 'GET_ALL_LEAVE_REQUEST';
export const GET_ALL_LEAVE_SUCCESS = 'GET_ALL_LEAVE_SUCCESS';
export const GET_ALL_LEAVE_FAIL = 'GET_ALL_LEAVE_FAIL';

export const APPROVE_LEAVE_REQUEST = 'APPROVE_LEAVE_REQUEST';
export const APPROVE_LEAVE_SUCCESS = 'APPROVE_LEAVE_SUCCESS';
export const APPROVE_LEAVE_FAIL = 'APPROVE_LEAVE_FAIL';

export const REJECT_LEAVE_REQUEST = 'REJECT_LEAVE_REQUEST';
export const REJECT_LEAVE_SUCCESS = 'REJECT_LEAVE_SUCCESS';
export const REJECT_LEAVE_FAIL = 'REJECT_LEAVE_FAIL';

export const DELETE_LEAVE_REQUEST = 'DELETE_LEAVE_REQUEST';
export const DELETE_LEAVE_SUCCESS = 'DELETE_LEAVE_SUCCESS';
export const DELETE_LEAVE_FAIL = 'DELETE_LEAVE_FAIL';
