export const USER_LEAVE_DETAILS_REQUEST = 'USER_LEAVE_DETAILS_REQUEST';
export const USER_LEAVE_DETAILS_SUCCESS = 'USER_LEAVE_DETAILS_SUCCESS';
export const USER_LEAVE_DETAILS_FAIL = 'USER_LEAVE_DETAILS_FAIL';

export const CREATE_LEAVE_REQUEST = 'CREATE_LEAVE_REQUEST';
export const CREATE_LEAVE_SUCCESS = 'CREATE_LEAVE_SUCCESS';
export const CREATE_LEAVE_FAIL = 'CREATE_LEAVE_FAIL';