export const USER_LEAVE_DETAILS_REQUEST = 'USER_LEAVE_DETAILS_REQUEST';
export const USER_LEAVE_DETAILS_SUCCESS = 'USER_LEAVE_DETAILS_SUCCESS';
export const USER_LEAVE_DETAILS_FAIL = 'USER_LEAVE_DETAILS_FAIL';
