export const MY_MEETINGS_REQUEST = 'MY_MEETINGS_REQUEST';
export const MY_MEETINGS_SUCCESS = 'MY_MEETINGS_SUCCESS';
export const MY_MEETINGS_FAIL = 'MY_MEETINGS_FAIL';

export const SCHEDULE_MEETING_REQUEST = 'SCHEDULE_MEETING_REQUEST';
export const SCHEDULE_MEETING_SUCCESS = 'SCHEDULE_MEETING_SUCCESS';
export const SCHEDULE_MEETING_FAIL = 'SCHEDULE_MEETING_FAIL';

export const EDIT_MEETING_REQUEST = 'EDIT_MEETING_REQUEST';
export const EDIT_MEETING_SUCCESS = 'EDIT_MEETING_SUCCESS';
export const EDIT_MEETING_FAIL = 'EDIT_MEETING_FAIL';

export const CANCEL_MEETING_REQUEST = 'CANCEL_MEETING_REQUEST';
export const CANCEL_MEETING_SUCCESS = 'CANCEL_MEETING_SUCCESS';
export const CANCEL_MEETING_FAIL = 'CANCEL_MEETING_FAIL';
