export const MY_MEETINGS_REQUEST = 'MY_MEETINGS_REQUEST';
export const MY_MEETINGS_SUCCESS = 'MY_MEETINGS_SUCCESS';
export const MY_MEETINGS_FAIL = 'MY_MEETINGS_FAIL';

export const CANCEL_MEETING_REQUEST = 'CANCEL_MEETING_REQUEST';
export const CANCEL_MEETING_SUCCESS = 'CANCEL_MEETING_SUCCESS';
export const CANCEL_MEETING_FAIL = 'CANCEL_MEETING_FAIL';
