export const USER_PROJECT_DETAILS_REQUEST = 'USER_PROJECT_DETAILS_REQUEST';
export const USER_PROJECT_DETAILS_SUCCESS = 'USER_PROJECT_DETAILS_SUCCESS';
export const USER_PROJECT_DETAILS_FAIL = 'USER_PROJECT_DETAILS_FAIL';

export const PROJECT_DETAILS_BY_ID_REQUEST = 'PROJECT_DETAILS_BY_ID_REQUEST';
export const PROJECT_DETAILS_BY_ID_SUCCESS = 'PROJECT_DETAILS_BY_ID_SUCCESS';
export const PROJECT_DETAILS_BY_ID_FAIL = 'PROJECT_DETAILS_BY_ID_FAIL';
