export const USER_PROJECT_DETAILS_REQUEST = 'USER_PROJECT_DETAILS_REQUEST';
export const USER_PROJECT_DETAILS_SUCCESS = 'USER_PROJECT_DETAILS_SUCCESS';
export const USER_PROJECT_DETAILS_FAIL = 'USER_PROJECT_DETAILS_FAIL';
