export const USER_PROJECT_DETAILS_REQUEST = 'USER_PROJECT_DETAILS_REQUEST';
export const USER_PROJECT_DETAILS_SUCCESS = 'USER_PROJECT_DETAILS_SUCCESS';
export const USER_PROJECT_DETAILS_FAIL = 'USER_PROJECT_DETAILS_FAIL';

export const PROJECT_DETAILS_BY_ID_REQUEST = 'PROJECT_DETAILS_BY_ID_REQUEST';
export const PROJECT_DETAILS_BY_ID_SUCCESS = 'PROJECT_DETAILS_BY_ID_SUCCESS';
export const PROJECT_DETAILS_BY_ID_FAIL = 'PROJECT_DETAILS_BY_ID_FAIL';

export const ALL_PROJECT_DETAILS_REQUEST = 'ALL_PROJECT_DETAILS_REQUEST';
export const ALL_PROJECT_DETAILS_SUCCESS = 'ALL_PROJECT_DETAILS_SUCCESS';
export const ALL_PROJECT_DETAILS_FAIL = 'ALL_PROJECT_DETAILS_FAIL';

export const CREATE_PROJECT_REQUEST = 'CREATE_PROJECT_REQUEST';
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS';
export const CREATE_PROJECT_FAIL = 'CREATE_PROJECT_FAIL';

export const DELETE_PROJECT_REQUEST = 'DELETE_PROJECT_REQUEST';
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS';
export const DELETE_PROJECT_FAIL = 'DELETE _PROJECT_FAIL';
