export const GET_ALL_EXPERIENCES_REQUEST = 'GET_ALL_EXPERIENCES_REQUEST';
export const GET_ALL_EXPERIENCES_SUCCESS = 'GET_ALL_EXPERIENCES_SUCCESS';
export const GET_ALL_EXPERIENCES_FAIL = 'GET_ALL_EXPERIENCES_FAIL';

export const ADD_EXPERIENCE_REQUEST = 'ADD_EXPERIENCE_REQUEST';
export const ADD_EXPERIENCE_SUCCESS = 'ADD_EXPERIENCE_SUCCESS';
export const ADD_EXPERIENCE_FAIL = 'ADD_EXPERIENCE_FAIL';

export const REMOVE_EXPERIENCE_REQUEST = 'REMOVE_EXPERIENCE_REQUEST';
export const REMOVE_EXPERIENCE_SUCCESS = 'REMOVE_EXPERIENCE_SUCCESS';
export const REMOVE_EXPERIENCE_FAIL = 'REMOVE_EXPERIENCE_FAIL';

export const GET_USER_EXPERIENCES_REQUEST = 'GET_USER_EXPERIENCES_REQUEST';
export const GET_USER_EXPERIENCES_SUCCESS = 'GET_USER_EXPERIENCES_SUCCESS';
export const GET_USER_EXPERIENCES_FAIL = 'GET_USER_EXPERIENCES_FAIL';
