# name: Build and Deploy

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3

#       - name: Build Images
#         run: docker build -t prathibha097/management-build .

#       - name: Push Build Images to DockerHub
#         env:
#           DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#         run: |
#           echo $DOCKER_PASSWORD | docker login -u prathibha097 --password-stdin
#           docker push prathibha097/management-build

#       - name: Update Docker Container on EC2
#         env:
#           PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
#         run: |
#           echo "$PRIVATE_KEY" > key.pem
#           chmod 400 key.pem
#           ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -i key.pem ec2-user@ec2-34-217-133-161.us-west-2.compute.amazonaws.com << 'EOF'
#           docker pull prathibha097/management-build
#           docker stop management-container
#           docker rm -f management-container
#           docker run -p 5000:5000 --name=management-container-new --restart always -d prathibha097/management-build
#           docker update --link --volumes-from=management-container management-container-new
#           docker rename management-container-new management-container
#           exit
#           EOF

#       # - name: Remove Unused Docker Images
#       #   run: |
#       #     docker image rm -f prathibha097/management-build
#       #     docker system prune -f

name: Build, Deploy, and Set Up Load Balancer

on:
  push:
    branches:
      - main

jobs:
  build-deploy-and-load-balance:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        container_name: [management-container-1, management-container-2]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Images
        run: docker build -t prathibha097/management-build .

      - name: Push Build Images to DockerHub
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u prathibha097 --password-stdin
          docker push prathibha097/management-build

      - name: Update Docker Containers on EC2
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY" > key.pem
          chmod 400 key.pem

          ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -i key.pem ec2-user@ec2-34-217-133-161.us-west-2.compute.amazonaws.com << 'EOF'
          docker pull prathibha097/management-build

          # Remove old images and prune the Docker system
          docker image prune -af
          docker system prune -af

          # Stop the old container gracefully
          docker stop ${{ matrix.container_name }}
          docker rm ${{ matrix.container_name }}

          # Start the new container with a unique name (using timestamp)
          TIMESTAMP=$(date '+%Y%m%d%H%M%S')

          # Use dynamic port assignment for the second container
          docker run -d --name=${{ matrix.container_name }}-new-${TIMESTAMP} -P prathibha097/management-build

          exit
          EOF

      - name: Create Nginx Config Directory
        run: |
          # Create the sites-available directory if it doesn't exist
          sudo mkdir -p /etc/nginx/sites-available

      - name: Install Nginx (if not already installed)
        run: |
          sudo apt-get update
          sudo apt-get install -y nginx

      - name: Start Nginx (if not already running)
        run: |
          sudo service nginx start

      - name: Configure Nginx
        run: |
          # Create a new Nginx configuration file for the new containers
          cat << EOF | sudo tee /etc/nginx/sites-available/load_balancer
          upstream backend {
              server 34.217.133.161:5000;
              server 34.217.133.161:5001;
          }
          
          server {
              listen 80;
              location / {
                  proxy_pass http://backend;
              }
          }
          EOF

          # Create a symbolic link to enable the configuration
          sudo ln -s /etc/nginx/sites-available/load_balancer /etc/nginx/sites-enabled/load_balancer

          # Test the Nginx configuration for syntax errors
          sudo nginx -t

          # Reload Nginx to apply the new configuration
          sudo service nginx reload

      - name: Sleep to allow traffic to shift gradually
        run: sleep 10

      - name: Remove old Nginx configuration and start the new container
        run: |
          # Remove the old Nginx configuration
          sudo rm /etc/nginx/sites-available/${{ matrix.container_name }}
          sudo rm /etc/nginx/sites-enabled/${{ matrix.container_name }}
          sudo nginx -t
          sudo service nginx reload

          # Start the new container with the original name
          # Note: The dynamic port assignment returns the actual mapped port for the second container
          NEW_CONTAINER_PORT=$(docker port ${{ matrix.container_name }}-new-${TIMESTAMP} 5000 | cut -d ':' -f 2)
          docker stop ${{ matrix.container_name }}-new-${TIMESTAMP}
          docker rename ${{ matrix.container_name }}-new-${TIMESTAMP} ${{ matrix.container_name }}

          # Update the Nginx configuration with the correct mapped port for the second container
          sudo sed -i "s/server 34.217.133.161:5001;/server 34.217.133.161:${NEW_CONTAINER_PORT};/" /etc/nginx/sites-available/load_balancer
          sudo nginx -t
          sudo service nginx reload

      - name: Remove Unused Docker Images
        run: |
          docker image rm -f prathibha097/management-build



