name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Images
        run: docker build -t prathibha097/management .

      - name: Push Images to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push prathibha097/management

      - name: Update Docker Container on EC2
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY" > key.pem
          chmod 400 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@ec2-34-220-229-58.us-west-2.compute.amazonaws.com << EOF
          docker pull prathibha097/management
          docker stop management-container
          docker run -d -p 5001:5000 --name=management-container-new prathibha097/management
          docker update --link --volumes-from=management-container management-container-new
          docker rm -f management-container
          docker rename management-container-new management-container
          exit
          EOF
